id: P007012
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6885
  title: ཇོ་ནང་པའི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  volumes:
    23edbd12e574482fa60cb4d464cfa73e:
      image_group_id: I3CN6887
      title: ''
      volume_number: 1
      total_pages: 326
ebook_metadata:
  title: ཇོ་ནང་པའི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  sku: P007012
  cover: cover.jpg
  layers:
  - pagination
